### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by Blazephoenix** [amangautam1/flutter-musicplayer#8]
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method getSharedData on channel app.channel.shared.data))

I/flutter (28237): theme=null
method not available: ext.flutter.debugPaintmethod not available: ext.flutter.showPerformanceOverlaymethod not available: ext.flutter.repaintRainbowmethod not available: ext.flutter.timeDilationmethod not available: ext.flutter.debugAllowBannermethod not available: ext.flutter.debugPaintBaselinesEnabledmethod not available: ext.flutter.inspector.show

Testing on USB connected android device.

**Comment by ankur1305** [comment]
This Same Problem Caused with me Also..Please give solutions or something

**Comment by amangautam1** [comment]
The plugin apparently hasn't been registered on the platform side.

- Have you executed flutter run targeting that platform since you changed the pubspec file? This is needed to have Flutter inject plugin dependencies into the platform-specific parts of your app. Please note that hot restart/hot reload is not enough to trigger the injection.
- Does the GeneratedPluginRegistrant file that flutter run should have generated in your project contain a line registering the path provider plugin?
- Does your  MainActivity.java contain a call to GeneratedPluginRegistrant asking it to register itself?

**Comment by ankur1305** [comment]
![screenshot 7](https://user-images.githubusercontent.com/44199303/50779404-3c89d000-12c6-11e9-921d-ed10ec84d26c.png)
This is my MainActivity.java file..please suggest changes in it

**Comment by amangautam1** [comment]
Try to import project via github in intellij idea compiler.
